# fly.toml app configuration file generated for django-email on 2023-10-11T12:27:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-email"
primary_region = "ams"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"

[mounts]
  source = "django_email_data"
  destination = "/data"